<a href="https://colab.research.google.com/github/maryemmohamed9/Python-For-Data-Analysis/blob/main/BikeStore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Exploration**

> improt csv file

> get first 5 rows and last 5 rows

> exploring columns data types

> null values

> unique values

> sorting

In [3]:
import numpy as np
import pandas as pd
df2 = pd.read_csv('BikeStores.csv')
df2

,order_id,customers,city,state,order_date,total_units,revenue,product_name,category_name,brand_name,store_name,sales_rep
0,1,Johnathan Velazquez,Pleasanton,CA,1/1/2016,2,1199.98,Electra Townie Original 7D EQ - 2016,Cruisers Bicycles,Electra,Santa Cruz Bikes,Mireya Copeland
1,1,Johnathan Velazquez,Pleasanton,CA,1/1/2016,1,599.99,Electra Townie Original 7D EQ - Women's - 2016,Cruisers Bicycles,Electra,Santa Cruz Bikes,Mireya Copeland
2,1,Johnathan Velazquez,Pleasanton,CA,1/1/2016,2,3098.00,Surly Straggler - 2016,Cyclocross Bicycles,Surly,Santa Cruz Bikes,Mireya Copeland
3,1,Johnathan Velazquez,Pleasanton,CA,1/1/2016,1,2899.99,Trek Fuel EX 8 29 - 2016,Mountain Bikes,Trek,Santa Cruz Bikes,Mireya Copeland
4,1,Johnathan Velazquez,Pleasanton,CA,1/1/2016,2,3599.98,Trek Remedy 29 Carbon Frameset - 2016,Mountain Bikes,Trek,Santa Cruz Bikes,Mireya Copeland
...,...,...,...,...,...,...,...,...,...,...,...,...
4717,1614,Dorthey Jackson,Houston,TX,28/11/2018,1,1499.00,Surly Krampus - 2018,Mountain Bikes,Surly,Rowlett Bikes,Kali Vargas
4718,1614,Dorthey Jackson,Houston,TX,28/11/2018,2,4599.98,Trek Emonda ALR 6 - 2018,Road Bikes,Trek,Rowlett Bikes,Kali Vargas
4719,1615,Sarita Parks,Forney,TX,28/12/2018,1,899.99,Electra Tiger Shark 3i - 2018,Cruisers Bicycles,Electra,Rowlett Bikes,Kali Vargas
4720,1615,Sarita Parks,Forney,TX,28/12/2018,1,2499.99,Trek Domane SL 5 Disc - 2018,Road Bikes,Trek,Rowlett Bikes,Kali Vargas
4721,1615,Sarita Parks,Forney,TX,28/12/2018,2,4599.98,Trek Verve+ Lowstep - 2018,Electric Bikes,Trek,Rowlett Bikes,Kali Vargas

In [4]:
df2.head()

,order_id,customers,city,state,order_date,total_units,revenue,product_name,category_name,brand_name,store_name,sales_rep
0,1,Johnathan Velazquez,Pleasanton,CA,1/1/2016,2,1199.98,Electra Townie Original 7D EQ - 2016,Cruisers Bicycles,Electra,Santa Cruz Bikes,Mireya Copeland
1,1,Johnathan Velazquez,Pleasanton,CA,1/1/2016,1,599.99,Electra Townie Original 7D EQ - Women's - 2016,Cruisers Bicycles,Electra,Santa Cruz Bikes,Mireya Copeland
2,1,Johnathan Velazquez,Pleasanton,CA,1/1/2016,2,3098.00,Surly Straggler - 2016,Cyclocross Bicycles,Surly,Santa Cruz Bikes,Mireya Copeland
3,1,Johnathan Velazquez,Pleasanton,CA,1/1/2016,1,2899.99,Trek Fuel EX 8 29 - 2016,Mountain Bikes,Trek,Santa Cruz Bikes,Mireya Copeland
4,1,Johnathan Velazquez,Pleasanton,CA,1/1/2016,2,3599.98,Trek Remedy 29 Carbon Frameset - 2016,Mountain Bikes,Trek,Santa Cruz Bikes,Mireya Copeland

In [5]:
df2.tail()

,order_id,customers,city,state,order_date,total_units,revenue,product_name,category_name,brand_name,store_name,sales_rep
4717,1614,Dorthey Jackson,Houston,TX,28/11/2018,1,1499.00,Surly Krampus - 2018,Mountain Bikes,Surly,Rowlett Bikes,Kali Vargas
4718,1614,Dorthey Jackson,Houston,TX,28/11/2018,2,4599.98,Trek Emonda ALR 6 - 2018,Road Bikes,Trek,Rowlett Bikes,Kali Vargas
4719,1615,Sarita Parks,Forney,TX,28/12/2018,1,899.99,Electra Tiger Shark 3i - 2018,Cruisers Bicycles,Electra,Rowlett Bikes,Kali Vargas
4720,1615,Sarita Parks,Forney,TX,28/12/2018,1,2499.99,Trek Domane SL 5 Disc - 2018,Road Bikes,Trek,Rowlett Bikes,Kali Vargas
4721,1615,Sarita Parks,Forney,TX,28/12/2018,2,4599.98,Trek Verve+ Lowstep - 2018,Electric Bikes,Trek,Rowlett Bikes,Kali Vargas

In [8]:
df2.isna().sum()

order_id         0
customers        0
city             0
state            0
order_date       0
total_units      0
revenue          0
product_name     0
category_name    0
brand_name       0
store_name       0
sales_rep        0
dtype: int64

In [10]:
df2.city.nunique()

195

In [9]:
df2.state.unique()

array(['CA', 'NY', 'TX'], dtype=object)

In [18]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4722 entries, 0 to 4721
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       4722 non-null   int64
 1   customers      4722 non-null   object
 2   city           4722 non-null   object
 3   state          4722 non-null   object
 4   order_date     4722 non-null   object
 5   total_units    4722 non-null   int64
 6   revenue        4722 non-null   float64
 7   product_name   4722 non-null   object
 8   category_name  4722 non-null   object
 9   brand_name     4722 non-null   object
 10  store_name     4722 non-null   object
 11  sales_rep      4722 non-null   object
dtypes: float64(1), int64(2), object(9)
memory usage: 442.8+ KB

In [21]:
df2.duplicated().sum()

0

In [23]:
df2.sort_values(by ='order_id', ascending = True)

,order_id,customers,city,state,order_date,total_units,revenue,product_name,category_name,brand_name,store_name,sales_rep
0,1,Johnathan Velazquez,Pleasanton,CA,1/1/2016,2,1199.98,Electra Townie Original 7D EQ - 2016,Cruisers Bicycles,Electra,Santa Cruz Bikes,Mireya Copeland
1,1,Johnathan Velazquez,Pleasanton,CA,1/1/2016,1,599.99,Electra Townie Original 7D EQ - Women's - 2016,Cruisers Bicycles,Electra,Santa Cruz Bikes,Mireya Copeland
2,1,Johnathan Velazquez,Pleasanton,CA,1/1/2016,2,3098.00,Surly Straggler - 2016,Cyclocross Bicycles,Surly,Santa Cruz Bikes,Mireya Copeland
3,1,Johnathan Velazquez,Pleasanton,CA,1/1/2016,1,2899.99,Trek Fuel EX 8 29 - 2016,Mountain Bikes,Trek,Santa Cruz Bikes,Mireya Copeland
4,1,Johnathan Velazquez,Pleasanton,CA,1/1/2016,2,3599.98,Trek Remedy 29 Carbon Frameset - 2016,Mountain Bikes,Trek,Santa Cruz Bikes,Mireya Copeland
...,...,...,...,...,...,...,...,...,...,...,...,...
4716,1614,Dorthey Jackson,Houston,TX,28/11/2018,2,539.98,Electra Cruiser 1 - 2016/2017/2018,Cruisers Bicycles,Electra,Rowlett Bikes,Kali Vargas
4718,1614,Dorthey Jackson,Houston,TX,28/11/2018,2,4599.98,Trek Emonda ALR 6 - 2018,Road Bikes,Trek,Rowlett Bikes,Kali Vargas
4720,1615,Sarita Parks,Forney,TX,28/12/2018,1,2499.99,Trek Domane SL 5 Disc - 2018,Road Bikes,Trek,Rowlett Bikes,Kali Vargas
4719,1615,Sarita Parks,Forney,TX,28/12/2018,1,899.99,Electra Tiger Shark 3i - 2018,Cruisers Bicycles,Electra,Rowlett Bikes,Kali Vargas
4721,1615,Sarita Parks,Forney,TX,28/12/2018,2,4599.98,Trek Verve+ Lowstep - 2018,Electric Bikes,Trek,Rowlett Bikes,Kali Vargas

# Selecting and Filtering

In [24]:
##max rev
df2['revenue'].max()

23999.98

In [53]:
##state have the max rev
df2[df2['revenue']==df2['revenue'].max()]['state'].unique()

array(['NY'], dtype=object)

In [33]:
##category have the min rev
df2[df2['revenue']==df2['revenue'].max()]['category_name'].unique()

array(['Road Bikes'], dtype=object)

In [39]:
## total revenue
df2['revenue'].sum()

8578988.879999999

In [28]:
## total orders
df2['order_id'].count()

4722

In [29]:
## total quantity
df2['total_units'].sum()

7078

In [55]:
##which category has the min revenue
df2[df2['revenue']==df2['revenue'].min()]['category_name'].unique()

array(['Children Bicycles'], dtype=object)

In [59]:
##max revenue by category name
df2.groupby('category_name')['revenue'].max()

category_name
Children Bicycles        979.98
Comfort Bicycles        5199.98
Cruisers Bicycles       5999.98
Cyclocross Bicycles     7999.98
Electric Bikes          9999.98
Mountain Bikes         10599.98
Road Bikes             23999.98
Name: revenue, dtype: float64

In [49]:
##top state and category by revenue
df2.groupby(['category_name','state'])['revenue'].max()

category_name        state
Children Bicycles    CA         979.98
                     NY         979.98
                     TX         979.98
Comfort Bicycles     CA        5199.98
                     NY        1799.98
                     TX        1799.98
Cruisers Bicycles    CA        5999.98
                     NY        5999.98
                     TX        1799.98
Cyclocross Bicycles  CA        7999.98
                     NY        7999.98
                     TX        6999.98
Electric Bikes       CA        9999.98
                     NY        9999.98
                     TX        9999.98
Mountain Bikes       CA       10599.98
                     NY       10599.98
                     TX        9999.98
Road Bikes           CA       12999.98
                     NY       23999.98
                     TX       12999.98
Name: revenue, dtype: float64

In [54]:
df2.groupby('category_name') .agg(
    mean_rev=('revenue', np.mean),
    sum_rev=('revenue', np.sum))

<ipython-input-54-2ef7a02db32d>:1: FutureWarning: The provided callable <function mean at 0x7e70787f5000> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df2.groupby('category_name') .agg(
<ipython-input-54-2ef7a02db32d>:1: FutureWarning: The provided callable <function sum at 0x7e70787f40d0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df2.groupby('category_name') .agg(

                        mean_rev     sum_rev
category_name
Children Bicycles     419.294386   327888.21
Comfort Bicycles      816.586350   438506.87
Cruisers Bicycles     804.899158  1109151.04
Cyclocross Bicycles  3124.510156   799874.60
Electric Bikes       4812.437972  1020236.85
Mountain Bikes       2561.940583  3030775.71
Road Bikes           4953.357219  1852555.60